# Generated by Django 2.2 on 2018-11-14 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('altitude', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineSupply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('hospital', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='supply')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CM', 'Clinic Manager'), ('WP', 'Warehouse Personel'), ('DP', 'Dispatcher')], max_length=2)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_end', to='ASP.Location')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_start', to='ASP.Location')),
            ],
        ),
    ]
