# Generated by Django 2.2 on 2018-11-14 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASP.User')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASP.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASP.User')),
            ],
        ),
    ]
